SecureLogin App/securelogin/accounts/urls.py
from . import views
from django.urls import path

app_name = 'accounts'
urlpatterns = [
    path('', views.home, name="home"),
    path('profile/', views.index, name="index"),

    path('accounts/sign_up/', views.sign_up, name="sign-up"),
    path('accounts/logout/', views.user_logout, name='logout'),
    path('accounts/login/', views.user_login, name='login'),
]

SecureLogin App/securelogin/securelogin/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from accounts import views
from accounts.forms import MySetPasswordForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='registration/password/password_reset_done.html'),
         name='password_reset_done'),
    path('password_reset/', views.password_reset_request, name="password_reset"),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='registration/password/password_reset_complete.html'
         ),
         name='password_reset_complete'
    ),
    path('',include("accounts.urls")),
]

SecureLogin App/securelogin/accounts/models.py
from django.db import models
import datetime
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)


class MyUserManager(BaseUserManager):
    def create_user(self, username, email, password=None):
        if not email:
            raise ValueError('Users must have an email address')
        if not username:
            raise ValueError('Users must have valid username')
        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password=None):
        user = self.create_user(
            username,
            email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    username = models.CharField(verbose_name='Username', max_length=255, unique=True,)
    fullname = models.CharField(verbose_name='Full Name', max_length=255,)
    email = models.EmailField(verbose_name='Email address', max_length=255, unique=True,)
    login_attempts = models.IntegerField(verbose_name='No. of failed attempted logins', default=0, )
    blocked_time = models.DateTimeField(
        verbose_name='Duration till which user is temporarily blocked',
        default=datetime.datetime.now() + datetime.timedelta(minutes=10),
    )
    password_expiry = models.DateTimeField(default=datetime.datetime.now() + datetime.timedelta(minutes=20),)

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.username

    def full_name(self):
        return self.fullname

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

SecureLogin App/securelogin/accounts/forms.py
from django import forms
from django.contrib.auth.admin import UserAdmin as BaseUserAdmin
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.core.exceptions import ValidationError
from accounts.models import MyUser
from django.contrib.auth.forms import SetPasswordForm
import datetime


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = MyUser
        fields = ('username', 'fullname', 'email')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = MyUser
        fields = ('username', 'fullname', 'email', 'password', 'is_active', 'is_admin')


class UserAdmin(BaseUserAdmin):
    form = UserChangeForm
    add_form = UserCreationForm

    list_display = ('username', 'is_admin')
    list_filter = ('is_admin',)
    fieldsets = (
        (None, {'fields': ('username', 'password')}),
        ('Personal info', {'fields': ('email', 'fullname')}),
        ('Permissions', {'fields': ('is_admin',)}),
    )
    add_fieldsets = (
        (None, {
            'classes': ('wide',),
            'fields': ('username', 'fullname', 'email', 'password1', 'password2'),
        }),
    )
    search_fields = ('username',)
    ordering = ('username',)
    filter_horizontal = ()


class MySetPasswordForm(SetPasswordForm):

    def save(self, *args, commit=True, **kwargs):
        user = super().save(commit=False)
        user.is_active = True
        if commit:
            user.login_attempts = 0
            user.blocked_time = datetime.datetime.now()
            user.password_expiry = datetime.datetime.now() + datetime.timedelta(minutes=10)
            user.save()
        return user

SecureLogin App/securelogin/accounts/views.py
import datetime
from .forms import UserCreationForm
from accounts.models import MyUser
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail, BadHeaderError
from django.db.models.query_utils import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode


def home(request):
    return render(request,'accounts/home.html')


@login_required
def index(request):
    return render(request,'accounts/index.html')


@login_required
def user_logout(request):
    logout(request)
    return redirect("accounts:home")


def sign_up(request):
    if request.user.is_authenticated:
        logout(request)
    context = {}
    form = UserCreationForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            form.login_attempts = 0
            form.blocked_time = datetime.datetime.now()
            form.password_expiry = datetime.datetime.now() + datetime.timedelta(minutes=10)
            user = form.save()
            login(request,user)
            return redirect('accounts:index')
    context['form']=form
    return render(request,'registration/sign_up.html',context)


def user_login(request):
    if request.user.is_authenticated:
        logout(request)
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        current_time = datetime.datetime.now()
        if user:
            if user.blocked_time.timestamp() < current_time.timestamp():
                user.login_attempts = 0
            if user.login_attempts == 5:
                user.blocked_time = current_time +  datetime.timedelta(minutes=5)
            if user.login_attempts >= 5 and user.blocked_time.timestamp() >= current_time.timestamp():
                # User has been temporarily blocked from service
                return render(request, 'registration/login.html',
                              {'error_message': "You have exceeded maximum the number of attempts."
                                                "Please wait for few hours before attempting again!"})
            if user.password_expiry.timestamp() <= current_time.timestamp():
                # User's password has expired
                messages.success(request, "Your password has expired. "
                                                "Kindly reset your password to access your account again!")
                return redirect("password_reset")
            user.login_attempts = 0
            user.blocked_time = current_time
            user.password_expiry = current_time + datetime.timedelta(minutes=10)
            user.save()
            login(request, user)
            return redirect("accounts:index")
        else:
            try:
                user = MyUser.objects.get(username=username)
            except:
                # No user with that Username exists
                return render(request, 'registration/login.html',
                              {'error_message': "Invalid login details provided.\nLogin failed."})
            else:
                # User provided wrong password
                user.login_attempts += 1
                user.save()
                if user.login_attempts == 5:
                    user.blocked_time = current_time +  datetime.timedelta(minutes=5)
                    user.save()
                if user.login_attempts >= 5 and user.blocked_time.timestamp() >= current_time.timestamp():
                    return render(request, 'registration/login.html',
                                  {'error_message': "You have exceeded maximum the number of attempts. "
                                                    "Please wait for few hours before attempting again!"})
                else:
                    message = "You have made " + str(user.login_attempts) + \
                              " number of unsuccessful attempts. After " + str(5 - user.login_attempts) + \
                              " more wrong attempts, your account will be temporarily deactivated."
                    return render(request, 'registration/login.html', {"error_message": message})
    else:
        return render(request, 'registration/login.html', {'error_message': None})


def password_reset_request(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = MyUser.objects.filter(Q(email=data))
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "registration/password/password_reset_email.txt"
                    c = {
                        "email": user.email,
                        'domain': '127.0.0.1:8000',
                        'site_name': 'Website',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(subject, email, 'admin@example.com' , [user.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    messages.success(request, 'A message with reset password instructions has been sent to your inbox.')
                    return redirect("password_reset_done")
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="registration/password/password_reset.html",
                  context={"password_reset_form":password_reset_form})

SecureLogin App/securelogin/accounts/templates/accounts/home.html
{% extends "base.html" %}
{% load static %}

{% block title %}SecureLogin HomePage{% endblock %}

{% block content %}
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <div class="alert alert-primary" role="alert">
            {{ message }}
        </div>
        {% endfor %}
    </ul>
    {% endif %}
    <div class="row align-items-center justify-content-center text-center">
        <div class="col-lg-10 align-self-end">
            <h1 class="text-black font-weight-bold">Secure Login</h1><br>
            <h3 class="text-uppercase text-black font-weight-bold">Your favorite Authentication platform</h3>
            <hr class="divider my-4">
        </div>
        <br>
        {% if user.is_authenticated %}
            <div class="row">
                <div class="col">
                   <div class="col-lg-12 align-self-baseline">
                        <p class="text-black-75 font-weight-light mb-5">Access your profile here</p>
                        <a class="btn btn-primary btn-xl js-scroll-trigger" href="{% url 'accounts:index' %}">My Profile</a>
                   </div>
                </div>
                <div class="col">
                    <div class="col-lg-12 align-self-baseline">
                        <p class="text-black-75 font-weight-light mb-5">Want to leave?<br>Logout here!</p>
                        <a class="btn btn-primary btn-xl js-scroll-trigger" href="{% url 'accounts:logout' %}">Logout</a>
                    </div>
                </div>
            </div>

                <div class="row">
                        <div class="col">
                            <div class="col-lg-12 align-self-baseline">
                                <p class="text-black-75 font-weight-light mb-5">Forgot password or password expired?<br>Reset here!</p>
                                <a class="btn btn-primary btn-xl js-scroll-trigger" href="{% url 'password_reset' %}">Reset Password</a>
                            </div>
                        </div>
                </div>
        {% else %}
            <div class="row">
                <div class="col">
                   <div class="col-lg-12 align-self-baseline">
                        <p class="text-black-75 font-weight-light mb-5">Start exploring more in the world of security and authentication</p>
                        <a class="btn btn-primary btn-xl js-scroll-trigger" href="{% url 'accounts:sign-up' %}">Sign Up</a>
                    </div>
                </div>
                <div class="col">
                    <div class="col-lg-12 align-self-baseline">
                        <p class="text-black-75 font-weight-light mb-5">Already have an account?<br>Login here!</p>
                        <a class="btn btn-primary btn-xl js-scroll-trigger" href="{% url 'accounts:login' %}">Login</a>
                    </div>
                </div>
                <div class="row">
                        <div class="col">
                            <div class="col-lg-12 align-self-baseline">
                                <p class="text-black-75 font-weight-light mb-5">Forgot password or password expired?<br>Reset here!</p>
                                <a class="btn btn-primary btn-xl js-scroll-trigger" href="{% url 'password_reset' %}">Reset Password</a>
                            </div>
                        </div>
                </div>
            </div>
        <br>
        {% endif %}
    </div>
<br>
{% endblock %}

SecureLogin App/securelogin/accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}SecureLogin Profile{% endblock %}

{% block content %}
<div class="row align-items-center justify-content-center text-center">
    <div class="col-lg-10 align-self-end">
        <h1 class="text-black font-weight-bold">Welcome {{user.fullname}} to SecureLogin</h1><br>
        <hr class="divider my-4">
    </div>
</div>

<div class="alert alert-info" role="alert">
    Your password expires on {{user.password_expiry}} IST. Kindly reset password before that. Else you will be unable to access your account without resetting the password
</div>
<br>
<br>
<div class="row align-items-center justify-content-center text-center">
    <div class="row">
        <div class="col">
            <div class="col-lg-12 align-self-baseline">
                <p class="text-black-75 font-weight-light mb-5">Reset Password here</p>
                <a class="btn btn-primary" href="{% url 'password_reset' %}">Reset Password</a>
            </div>
        </div>
        <div class="col">
            <div class="col-lg-12 align-self-baseline">
                <p class="text-black-75 font-weight-light mb-5">Want to leave?<br>Logout here!</p>
                <a class="btn btn-primary" href="{% url 'accounts:logout' %}">Logout</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}